# Custom MinGW toolchain file for vcpkg
# This tells vcpkg to use MinGW GCC for building dependencies on Windows

set(CMAKE_C_COMPILER gcc)
set(CMAKE_CXX_COMPILER g++)
set(CMAKE_AR ar)
set(CMAKE_RANLIB ranlib)
set(CMAKE_STRIP strip)

# Tell CMake this is a MinGW environment
set(MINGW TRUE)
set(CMAKE_SYSTEM_NAME Windows)

# IMPORTANT: Disable --out-implib flag to prevent WinMain errors
# The --out-implib flag causes MinGW to use GUI startup files expecting WinMain
# instead of console startup files expecting main()
set(CMAKE_IMPORT_LIBRARY_SUFFIX "" CACHE STRING "Disable import library generation for executables" FORCE)

# Console mode is the default for MinGW - no -mconsole flag needed
# Just ensure WIN32_EXECUTABLE is FALSE (set in vcpkg triplet)
set(CMAKE_WIN32_EXECUTABLE FALSE CACHE BOOL "Default to console executables" FORCE)

# CRITICAL: Override the link rule to remove --out-implib flag
# CMake's MinGW platform module adds --out-implib unconditionally
# which causes MinGW to use GUI startup files (crtexewin.o) expecting WinMain
# instead of console startup files (crt2.o) expecting main()
# We override CMAKE_CXX_LINK_EXECUTABLE to filter out --out-implib
set(CMAKE_CXX_LINK_EXECUTABLE
    "<CMAKE_CXX_COMPILER> <FLAGS> <CMAKE_CXX_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>"
    CACHE STRING "Link command without --out-implib" FORCE
)

# Also override C linker for completeness
set(CMAKE_C_LINK_EXECUTABLE
    "<CMAKE_C_COMPILER> <FLAGS> <CMAKE_C_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>"
    CACHE STRING "Link command without --out-implib" FORCE
)

# Post-configure patch to remove --out-implib from build.ninja
# This runs after build.ninja is generated by CMake
set(_patch_ninja_script "${CMAKE_BINARY_DIR}/patch_ninja.cmake")
file(WRITE "${_patch_ninja_script}"
"if(EXISTS \"${CMAKE_BINARY_DIR}/build.ninja\")
  execute_process(
    COMMAND sed -i.bak \"s/-Wl,--out-implib,[^ ]* //g\" \"${CMAKE_BINARY_DIR}/build.ninja\"
    RESULT_VARIABLE _sed_result
    ERROR_QUIET
  )
  if(_sed_result EQUAL 0)
    message(STATUS \"Patched build.ninja to remove --out-implib flag\")
  endif()
endif()
")
set(CMAKE_PROJECT_INCLUDE "${_patch_ninja_script}" CACHE FILEPATH "Post-configure script" FORCE)

# Ensure we find the MinGW compiler
find_program(CMAKE_C_COMPILER gcc)
find_program(CMAKE_CXX_COMPILER g++)
find_program(CMAKE_AR ar)
find_program(CMAKE_RANLIB ranlib)
find_program(CMAKE_STRIP strip)
