---
name: Linux Builds

on:
  workflow_call:

permissions:
  contents: read

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        include:
          #####################################################################
          #                          x86_64 builds                            #
          #####################################################################

          - build_arch: amd64
            build_dist: ubuntu
            build_type: gcc-release-shared-ninja-split

          - build_arch: amd64
            build_dist: ubuntu
            build_type: gcc-debug-shared-noperfmon-ninja-split

          - build_arch: amd64
            build_dist: ubuntu
            build_type: clang-reldbg-shared-asan-ninja

          - build_arch: amd64
            build_dist: ubuntu
            build_type: clang-reldbg-shared-ubsan-ninja

          - build_arch: amd64
            build_dist: ubuntu
            build_type: clang-debug-shared-tsan-ninja

          - build_arch: amd64
            build_dist: ubuntu
            build_type: clang-debug-coverage-ninja

          - build_arch: amd64
            build_dist: fedora
            build_type: gcc-release-ninja-split

          - build_arch: amd64
            build_dist: fedora
            build_type: clang-release-shared-ninja-full

          - build_arch: amd64
            build_dist: arch
            build_type: gcc-release-noman-ninja-split

          - build_arch: amd64
            build_dist: arch
            build_type: gcc-release-shared-ninja-split

          - build_arch: amd64
            build_dist: arch
            build_type: gcc-debug-shared-ninja-full

          - build_arch: amd64
            build_dist: arch
            build_type: clang-release-shared-ninja-full

          - build_arch: amd64
            build_dist: alpine
            build_type: gcc-release-ninja-static

          - build_arch: amd64
            build_dist: alpine
            build_type: gcc-release-lto-ninja-static

          - build_arch: amd64
            build_dist: alpine
            build_type: clang-release-lto-ninja-static

          - build_arch: amd64
            build_dist: alpine
            build_type: clang-relsize-lto-ninja-static

          - build_arch: amd64
            build_dist: alpine
            build_type: clang-relsize-libressl-lto-ninja-static

          - build_arch: amd64
            build_dist: alpine
            build_type: clang-relsize-minimal-libressl-lto-ninja-static

          - build_arch: amd64
            build_dist: alpine
            build_type: clang-reldbg-stacktrace-ninja-static

          #####################################################################
          #                          aarch64 builds                           #
          #####################################################################

          - build_arch: arm64v8
            build_dist: debian
            build_type: gcc-release-dev-make-full

          - build_arch: arm64v8
            build_dist: debian
            build_type: clang-debug-shared-ninja-split

          - build_arch: arm64v8
            build_dist: suse
            build_type: gcc-release-ninja-split

          - build_arch: arm64v8
            build_dist: suse
            build_type: clang-debug-dev-shared-make-full

          - build_arch: arm64v8
            build_dist: ubuntu-2204
            build_type: gcc-release-shared-ninja-split

          - build_arch: arm64v8
            build_dist: ubuntu-2204
            build_type: gcc-debug-shared-ninja-full

          - build_arch: arm64v8
            build_dist: ubuntu-2204
            build_type: clang-release-ninja-split

          - build_arch: arm64v8
            build_dist: ubuntu
            build_type: gcc-debug-shared-ninja-full

          - build_arch: arm64v8
            build_dist: ubuntu
            build_type: clang-release-shared-ninja-full

          - build_arch: arm64v8
            build_dist: ubuntu
            build_type: oldgcc-debug-shared-make-split

          - build_arch: arm64v8
            build_dist: ubuntu
            build_type: oldclang-debug-shared-make-split

          - build_arch: arm64v8
            build_dist: fedora
            build_type: gcc-release-shared-make-full

          - build_arch: arm64v8
            build_dist: fedora
            build_type: gcc-debug-shared-ninja-split

          - build_arch: arm64v8
            build_dist: fedora
            build_type: clang-release-shared-ninja-full

          - build_arch: arm64v8
            build_dist: alpine
            build_type: gcc-release-ninja-static

          - build_arch: arm64v8
            build_dist: alpine
            build_type: clang-release-ninja-static

          - build_arch: arm64v8
            build_dist: alpine
            build_type: clang-relsize-lto-ninja-static

          - build_arch: arm64v8
            build_dist: alpine
            build_type: clang-relsize-libressl-lto-ninja-static

          - build_arch: arm64v8
            build_dist: alpine
            build_type: clang-relsize-minimal-libressl-lto-ninja-static

          - build_arch: arm64v8
            build_dist: alpine
            build_type: clang-reldbg-stacktrace-ninja-static

          #####################################################################
          #                          riscv64 builds                           #
          #####################################################################

          - build_arch: riscv64
            build_dist: debian
            build_type: gcc-release-ninja-full

          #####################################################################
          #                       aarch64 builds (cross)                      #
          #####################################################################

          - build_arch: amd64
            build_dist: alpine
            build_type: clang-relsize-libressl-lto-ninja-static
            cross_arch: aarch64

          #####################################################################
          #                       riscv64 builds (cross)                      #
          #####################################################################

          - build_arch: amd64
            build_dist: alpine
            build_type: clang-relsize-libressl-lto-ninja-static
            cross_arch: riscv64

          - build_arch: amd64
            build_dist: alpine
            build_type: clang-relsize-minimal-libressl-lto-ninja-static
            cross_arch: riscv64

          #####################################################################
          #                        i386 builds (cross)                        #
          #####################################################################

          - build_arch: amd64
            build_dist: alpine
            build_type: clang-relsize-lto-ninja-static
            cross_arch: i386

          - build_arch: amd64
            build_dist: alpine
            build_type: clang-relsize-libressl-lto-ninja-static
            cross_arch: i386

          - build_arch: amd64
            build_dist: alpine
            build_type: clang-relsize-minimal-libressl-lto-ninja-static
            cross_arch: i386

          #####################################################################
          #                         arm builds (cross)                        #
          #####################################################################

          - build_arch: amd64
            build_dist: alpine
            build_type: clang-relsize-lto-ninja-static
            cross_arch: arm

          - build_arch: amd64
            build_dist: alpine
            build_type: clang-relsize-libressl-lto-ninja-static
            cross_arch: arm

          - build_arch: amd64
            build_dist: alpine
            build_type: clang-relsize-minimal-libressl-lto-ninja-static
            cross_arch: arm

          #####################################################################
          #                       ppc64le builds (cross)                      #
          #####################################################################

          - build_arch: amd64
            build_dist: alpine
            build_type: gcc-release-lto-ninja-static
            cross_arch: ppc64le

          - build_arch: amd64
            build_dist: alpine
            build_type: gcc-release-libressl-lto-ninja-static
            cross_arch: ppc64le

          - build_arch: amd64
            build_dist: alpine
            build_type: gcc-release-minimal-libressl-lto-ninja-static
            cross_arch: ppc64le

          #####################################################################
          #                        ppc64 builds (cross)                       #
          #####################################################################

          - build_arch: amd64
            build_dist: alpine
            build_type: gcc-release-libressl-ninja-static
            cross_arch: ppc64
            skip_fuse_tests: true

          - build_arch: amd64
            build_dist: alpine
            build_type: gcc-release-minimal-libressl-ninja-static
            cross_arch: ppc64
            skip_fuse_tests: true

          #####################################################################
          #                     loongarch64 builds (cross)                    #
          #####################################################################

          - build_arch: amd64
            build_dist: alpine
            build_type: clang-relsize-lto-ninja-static
            cross_arch: loongarch64

          - build_arch: amd64
            build_dist: alpine
            build_type: clang-relsize-minimal-lto-ninja-static
            cross_arch: loongarch64

          #####################################################################
          #                        s390x builds (cross)                       #
          #####################################################################

          - build_arch: amd64
            build_dist: alpine
            build_type: gcc-release-lto-ninja-static
            cross_arch: s390x
            skip_fuse_tests: true

          - build_arch: amd64
            build_dist: alpine
            build_type: gcc-release-minimal-lto-ninja-static
            cross_arch: s390x
            skip_fuse_tests: true

    uses: ./.github/workflows/docker-run-build.yml
    with:
      build_type: ${{ matrix.build_type }}
      build_arch: ${{ matrix.build_arch }}
      build_dist: ${{ matrix.build_dist }}
      cross_arch: ${{ matrix.cross_arch }}
      skip_slow_tests: ${{ matrix.skip_slow_tests || false }}
      skip_fuse_tests: ${{ matrix.skip_fuse_tests || false }}
      build_from_tarball: true
      upload_coverage: ${{ matrix.build_type == 'clang-debug-coverage-ninja' }}
      upload_artifacts: ${{ endsWith(matrix.build_type, '-static') }}